_BASE_: "../../../base-prompt_fourier.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: vtab-clevr(task="closest_object_distance")
  DATAPATH: "/disks/sata2/kaiqian/workspace/VFPT/data/vtab-1k/"  #TODO: need to specify here
  NUMBER_CLASSES: 6
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
