NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "output_vfpt_dct_gating"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "fpt"
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: []
  # --- [新增] 这里是控制 DCT 和 Gating 的核心参数 ---
  PROMPT_FOURIER:
    FOURIER_MODE: "dct"    # 将变换模式改为 DCT
    USE_GATING: True       # 开启自适应门控机制
  # ------------------------------------------------
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
DATA:
  NAME: "test"
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "sup_vitb16_224"
  BATCH_SIZE: 64